<Project>
<ItemGroup Label="Update">
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="7.0.8" PrivateAssets="all" />
	<PackageReference Update="Aspire.Hosting.JavaScript" Version="13.4.6" />
	<PackageReference Update="Aspire.Hosting.Redis" Version="13.4.6" />

	<PackageReference Update="Microsoft.EntityFrameworkCore" Version="10.0.10" />
	<PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
	<PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
	<PackageReference Update="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />

	<PackageReference Update="Aspire.StackExchange.Redis.OutputCaching" Version="13.4.6" />
	<PackageReference Update="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
	<PackageReference Update="Microsoft.Extensions.ServiceDiscovery" Version="10.8.0" />
	<PackageReference Update="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
	<PackageReference Update="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
	<PackageReference Update="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
	<PackageReference Update="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
	<PackageReference Update="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
	<PackageReference Update="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Update="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />

  </ItemGroup>

  <ItemGroup Label="Include">
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.91" PrivateAssets="all" />
  </ItemGroup>
</Project>